
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface QuestionOption {
  id: string; // Unique ID for the option
  text: string;
}

export interface Question {
  id: string; // Unique ID for the question
  text: string;
  options: QuestionOption[];
  correctOptionId: string; // ID of the correct QuestionOption
}

// Main user table (proctorX)
export interface ProctorXTableType {
  user_id: string; // Primary Key (e.g., 6-character ID, generated by app)
  email: string; // User's login email (must be unique)
  pass: string;  // Plaintext password (SECURITY RISK - FOR TESTING ONLY)
  name: string;  // User's full name
  role: 'student' | 'teacher'; // User's role
  avatar_url: string | null; // URL for the user's avatar
  created_at?: string;
}

export type ExamStatus = 'Published' | 'Ongoing' | 'Completed';

export interface Database {
  public: {
    Tables: {
      proctorX: {
        Row: ProctorXTableType;
        Insert: Omit<ProctorXTableType, 'created_at' | 'user_id'> & { user_id?: string }; // user_id is app-generated
        Update: Partial<Omit<ProctorXTableType, 'created_at' | 'user_id' | 'email'>>;
      };
      ExamX: {
        Row: {
          exam_id: string; // UUID
          teacher_id: string; // Foreign key to proctorX.user_id
          title: string;
          description: string | null;
          duration: number; // in minutes
          allow_backtracking: boolean;
          questions: Question[] | null;
          exam_code: string; // Unique short code for students to join
          status: ExamStatus;
          start_time: string | null; // ISO string for start datetime
          end_time: string | null;   // ISO string for end datetime
          created_at: string;
          updated_at: string;
        };
        Insert: {
          exam_id?: string; // UUID, can be auto-generated by DB
          teacher_id: string;
          title: string;
          description?: string | null;
          duration: number;
          allow_backtracking?: boolean;
          questions?: Question[] | null;
          exam_code: string;
          status?: ExamStatus; // Defaults to 'Published'
          start_time: string; // Made non-optional if status is Published
          end_time: string;   // Made non-optional if status is Published
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<{
          title: string;
          description: string | null;
          duration: number;
          allow_backtracking: boolean;
          questions: Question[] | null;
          status: ExamStatus;
          start_time: string | null;
          end_time: string | null;
          updated_at: string;
        }>;
      };
      ExamSubmissionsX: {
        Row: {
          submission_id: string; // UUID
          exam_id: string; // UUID, Foreign key to ExamX
          student_user_id: string; // Foreign key to proctorX.user_id
          answers: Json | null; // e.g., { "questionId1": "selectedOptionId1", ... }
          status: 'In Progress' | 'Completed';
          score: number | null; // Percentage
          started_at: string;
          submitted_at: string | null;
          flagged_events: Json | null; // Array of FlaggedEvent objects
        };
        Insert: {
          submission_id?: string;
          exam_id: string;
          student_user_id: string;
          answers?: Json | null;
          status?: 'In Progress' | 'Completed';
          score?: number | null;
          started_at?: string;
          submitted_at?: string | null;
          flagged_events?: Json | null;
        };
        Update: Partial<{
          answers: Json | null;
          status: 'In Progress' | 'Completed';
          score: number | null;
          submitted_at: string | null;
          flagged_events: Json | null;
        }>;
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

export type CustomUser = {
  user_id: string; // 6-char ID
  email: string;
  name: string | null;
  role: 'student' | 'teacher' | null;
  avatar_url: string | null;
};

export type ProctorXTable = Database['public']['Tables']['proctorX'];
export type Exam = Database['public']['Tables']['ExamX']['Row'];
export type ExamInsert = Database['public']['Tables']['ExamX']['Insert'];
export type ExamUpdate = Database['public']['Tables']['ExamX']['Update'];
export type ExamSubmission = Database['public']['Tables']['ExamSubmissionsX']['Row'];
export type ExamSubmissionInsert = Database['public']['Tables']['ExamSubmissionsX']['Insert'];
export type ExamSubmissionUpdate = Database['public']['Tables']['ExamSubmissionsX']['Update'];


export type FlaggedEventType =
  | 'visibility_hidden'
  | 'visibility_visible'
  | 'fullscreen_entered'
  | 'fullscreen_exited'
  | 'blur'
  | 'focus'
  | 'copy_attempt'
  | 'paste_attempt';

export interface FlaggedEvent {
  type: FlaggedEventType;
  timestamp: Date; // Will be stored as ISO string in JSONB
  studentId: string;
  examId: string;
  details?: string;
}
