
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface QuestionOption {
  id: string; // Unique ID for the option
  text: string;
}

export interface Question {
  id: string; // Unique ID for the question
  text: string;
  options: QuestionOption[];
  correctOptionId: string; // ID of the correct QuestionOption
}

// Main user table, storing credentials and basic info
export interface ProctorXTableType {
  user_id: string; // Primary Key (6-character ID, generated by app)
  email: string; // User's login email (must be unique)
  pass: string;  // Plaintext password (SECURITY RISK - FOR TESTING ONLY)
  name: string;  // User's full name
  role: 'student' | 'teacher'; // User's role
  created_at?: string;
}

export type ExamStatus = 'Draft' | 'Published' | 'Ongoing' | 'Completed';

export interface Database {
  public: {
    Tables: {
      proctorX: {
        Row: ProctorXTableType;
        Insert: Omit<ProctorXTableType, 'created_at'>;
        Update: Partial<Omit<ProctorXTableType, 'created_at'>>;
      };
      ExamX: {
        Row: {
          exam_id: string;
          teacher_id: string;
          title: string;
          description: string | null;
          duration: number;
          allow_backtracking: boolean;
          questions: Question[] | null;
          exam_code: string;
          status: ExamStatus;
          start_time: string | null; // ISO string
          end_time: string | null;   // ISO string
          created_at: string;
          updated_at: string;
        };
        Insert: {
          exam_id?: string;
          teacher_id: string;
          title: string;
          description?: string | null;
          duration: number;
          allow_backtracking?: boolean;
          questions?: Question[] | null;
          exam_code: string;
          status?: ExamStatus;
          start_time?: string | null;
          end_time?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          exam_id?: string;
          teacher_id?: string;
          title?: string;
          description?: string | null;
          duration?: number;
          allow_backtracking?: boolean;
          questions?: Question[] | null;
          exam_code?: string;
          status?: ExamStatus;
          start_time?: string | null;
          end_time?: string | null;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

export type CustomUser = {
  user_id: string;
  email: string;
  name: string | null;
  role: 'student' | 'teacher' | null;
};

export type ProctorXTable = Database['public']['Tables']['proctorX'];
export type ExamXTable = Database['public']['Tables']['ExamX'];
export type Exam = ExamXTable['Row'];

export type FlaggedEventType =
  | 'visibility_hidden'
  | 'visibility_visible'
  | 'fullscreen_entered'
  | 'fullscreen_exited'
  | 'blur'
  | 'focus';

export interface FlaggedEvent {
  type: FlaggedEventType;
  timestamp: Date;
  studentId: string;
  examId: string;
  details?: string;
}
